services:
  file_export_server:
    build:
      context: .
      dockerfile: dockerfile.server
    container_name: file_export_server
    environment:
      - EXPORT_DIR=/data/output
    volumes:
      - [path to output]:/data/output
    ports:
      - 9003:9003
networks: {}
